# Neoklassische Wachstumstheorie -- exogene Sparquote


~~~
**Kernbotschaften:**  

- Der Kapitalstock kann nicht aus sich heraus über ein bestimmtes Niveau hinaus wachsen.

- Das langfristige Wachstum des Einkommens pro Kopf wird durch *technischen Fortschritt* erklärt.

- Der Fortschritt ist im Modell *exogen*.

~~~

::: {.callout-note icon=false}

## Kernbotschaften 

- Der Kapitalstock kann nicht aus sich heraus über ein bestimmtes Niveau hinaus wachsen.

- Das langfristige Wachstum des Einkommens pro Kopf wird durch *technischen Fortschritt* erklärt.

- Der Fortschritt ist im Modell *exogen*.


:::

## Produktionsfunktion

Allgemeine Form Cobb-Douglas Produktionsfunktion

$Y=A{K}^{\alpha }{L}^{\beta }$

[oder das A vor das L?]:;

Annahme: Konstante Skalenerträge

$Y=A{K}^{\alpha }{L}^{\left(1-\alpha \right)}$

Für das Folgende nehmen wir zunächst an $A=L=1$



## Kapitalbildung

Geschlossene Volkswirtschaft

$I=S$

Exogene Sparquote $s$

${I}_t=S_t=s{Y}_t$

Veränderung des Kapitalstocks

${K}_{t+1}=\left(1-\delta \right){K}_t+{I}_t$

## Pro-Kopf-Größen

Pro-Kopf-Einkommen

$y=\frac{Y}{L}=\frac{A{K}^{\alpha }{L}^{1-\alpha }}{L}=\frac{A{K}^{\alpha }L}{L^{\alpha }L}=A{\left(\frac{K}{L}\right)}^{\alpha }$

Kapitalstock pro Kopf

$\frac{K_{t+1}}{L}=\left(1-\delta \right)\left(\frac{{K}_{t}}{\mathrm{L}}\right)+\mathrm{s}\left(\frac{{Y}_{t}}{\mathrm{L}}\right)$

oder kürzer

${k}_{t+1}=\left(1-\delta \right){k}_t+s{y}_t$

Pro-Kopf-Konsum

$c=\left(\frac{C}{L}\right)=\left(1-s\right)\left(\frac{Y}{L}\right)$

## Langfristiges Gleichgewicht

Die Produktion $Y$ wächst, wenn  
- $A$ wächst (Technischer Fortschritt)
- $L$ wächst (Bevölkerungswachstum)
- $K$ wächst (Kapitalakkumulation)

Fokus hier: $K$

Investitionen lassen den Kapitalstock wachsen. Abschreibungen (Verschleiß) lassen ihn schrumpfen.

Investitionen = Abschreibungen

$s{\left(\frac{\mathrm{K}}{\mathrm{L}}\right)}^{\alpha }=\delta \left(\frac{K}{L}\right)$

$\iff s=\delta {\left(\frac{\mathrm{K}}{\mathrm{L}}\right)}^{1-\alpha }$

$\iff \frac{s}{\delta }={\left(\frac{\mathrm{K}}{\mathrm{L}}\right)}^{1-\alpha }$

$\iff k=\left(\frac{K}{L}\right)={\left(\frac{s}{\delta}\right)}^{\frac{1}{1-\alpha }}$

$\iff y=\left(\frac{\mathrm{Y}}{\mathrm{L}}\right)={\left(\frac{s}{\delta}\right)}^{\frac{\alpha }{1-\alpha }}$

$\rightarrow$ Es gibt einen langfristigen Kapitalstock, der nicht mehr aus sich heraus wächst.

$\rightarrow$ Damit gibt es auch ein Langfristiges Einkommen und ein Langfristiges Konsumniveau

$\rightarrow$ Dies gilt *unabhängig* von einem Ausgangswert für den Kapitalstock

## Entwicklung des Kapitalstocks

```{python}
#|message: false
#|warning: false


import plotnine as gg
import numpy as np
import pandas as pd

# Parameter
alpha = 0.4
delta = 0.1
s = 0.2
L = 1 # einfachster Fall
n = 0 # Bevölkerungswachstum

# Zeitschritte
t = np.linspace(0, 100, 101)

# Kapitalakkumulation
##Vorbeteitung

K_t = np.zeros(len(t))
Y_t = np.zeros(len(t))
I_t = np.zeros(len(t))
L_t = np.zeros(len(t))
k_t = np.zeros(len(t))
y_t = np.zeros(len(t))

## Ausgangswerte

K_t[0] = 2
Y_t[0] = (K_t[0]**alpha)*(L**(1-alpha)) #CD-Funktion
I_t[0] = s*Y_t[0]
L_t[0] = L
y_t[0] = Y_t[0]/L_t[0]
k_t[0] = K_t[0]/L_t[0]

## Dynamik


for i in range(1, len(t)):

    K_t[i] = (1-delta)*K_t[i-1] + I_t[i-1]
    Y_t[i] = (K_t[i]**alpha) * (L**(1-alpha))
    I_t[i] = s*Y_t[i]
    L_t[i] = (1+n)*L_t[i-1]
    k_t[i] = K_t[i]/L_t[i]
    y_t[i] = Y_t[i]/L_t[i]



## In Datenframe speichern
df = pd.DataFrame({'t': t, 'Kapital': K_t, 'Y': Y_t,
                    'Investitionen': I_t, 'Abschreibungen': delta*K_t,
                    'Bevölkerung': L_t, 'Kapital pro Kopf': k_t,
                  'y': y_t})
      
```

```{python}
#|message: false
#|warning: false

#Grafiken


(gg.ggplot(df, gg.aes('t', 'Kapital pro Kopf')) + gg.geom_line() +
 gg.labs(x='Zeit', y='Kapital pro Kopf',
 title= "Kapital pro Kopf im Zeitverlauf")+
 gg.theme_light()
)
```

```{python}
#|message: false
#|warning: false


(gg.ggplot(df, gg.aes('t', 'Investitionen')) + gg.geom_line() +
gg.geom_line(gg.aes(y='Abschreibungen'), color= 'blue')+
 gg.labs(x='Zeit', y='Investitionen,  Abschreibungen',
 title="Investitionen und Abschreibungen im  Zeitverlauf")+
 gg.theme_light()
)

```

```{python}
#|message: false
#|warning: false


(gg.ggplot(df, gg.aes('Kapital pro Kopf', 'Abschreibungen')) + gg.geom_line() +
gg.geom_line(gg.aes(y='Investitionen'), color= 'blue')+
gg.labs(x='k', y='I,  Abschreibungen',
title="Investitionen und Abschreibungen als Funktion des Kapitalstocks")+
 gg.theme_light()
)
```

## Entwicklung des Einkommens

```{python}
#|message: false
#|warning: false



(gg.ggplot(df, gg.aes('t', 'y')) + gg.geom_line() +
 gg.labs(x='Zeit', y='Pro Kopf Einkommen')+
 gg.theme_light()
)


# Daten zeigen
# print(df)

```

## Sparquote für maximales Einkommen

$\iff y={\left(\frac{s}{\delta}\right)}^{\frac{\alpha }{1-\alpha }}$

Welche Sparquote maximiert das Einkommen? Ist das sinnvoll?

## Sparquote für maximalen Komsum

$c=(1-s)y=(1-s){\left(\frac{s}{\delta}\right)}^{\frac{\alpha }{1-\alpha }}$

Das sieht so aus, als könne es eine innere Lösung geben.

Finden wir ein Maximum?

```{python}
#| message: false
#| warning: false

# Goldene Regel

## Pro-Kopf Konsum

#y=(s/delta)**(alpha/(1-alpha))
#c=(1-s)*y

# schritte für s
si = np.linspace(0, 100, 101)

# Kapitalakkumulation
c_si = np.zeros(101)
si_si = np.zeros(len(si))
y_si = np.zeros(len(si))

for i in range(0, 100):

   si_si[i]=i/100
   c_si[i]= (1-i/100)*((i/(delta*100))**(alpha/(1-alpha)))
   y_si[i]=           ((i/(delta*100))**(alpha/(1-alpha)))


# Datenframe
df = pd.DataFrame({'Sparquote': si_si, 'Konsum': c_si,
                    'y': y_si, 'Ersparnis':si_si*y_si})

#print(df)

```

```{python}
#| message: false
#| warning: false
(gg.ggplot(df, gg.aes('Sparquote', 'Konsum')) + gg.geom_line() +
 gg.labs(x='Sparquote', y='Konsum')+
 gg.theme_light()
)

```

```{python}
#| message: false
#| warning: false

(gg.ggplot(df, gg.aes('Sparquote', 'y')) + gg.geom_line(color="green") +
 gg.geom_line(gg.aes(y='Ersparnis'), color="red")+
 gg.labs(x='Sparquote', y='y')+
 gg.theme_light()
)
```

Wie bestimmt sich denn nun die Sparquote für maximalen Konsum analytisch?

```{python}
#|message: false
#|warning: false
#|eval: false

from sympy import Symbol, solve, Eq, diff, simplify, print_latex


Y = Symbol('Y')
L= Symbol('L')
K= Symbol('K')
alpha= Symbol('alpha')
delta=Symbol('delta')
c=Symbol('c')
s=Symbol('s')


L=1

y=(s/delta)**(alpha/(1-alpha))

c=(1-s)*y


sol=diff(c, s)

print_latex(simplify(sol))
print(simplify(sol))

sol2=solve(Eq(sol, 0), s)

print(sol2)

#sol3=diff(y, s)
#print(sol3)

#sol4=solve(Eq(sol3, 0), s)
#print(sol4)
```

$\frac{\partial c}{\partial s}=\frac{\left(\frac{s}{\delta}\right)^{- \frac{\alpha}{\alpha - 1}} \left(- \alpha + s\right)}{s \left(\alpha - 1\right)}\overset{!}{=} 0$

$\iff s=\alpha$

$s^* = \alpha \rightarrow$ Spare das Kapitaleinkommen und konsumiere das Arbeitseinkommen!

## Bevölkerungswachstum

Annahme bisher: Konstante Bevölkerung.

Nun: Bevölkerung wächst mit der Rate $n$ so dass gilt: $L_{t+1}=(1+n)L_t$

Kapitalstock pro Kopf bleibt konstant, wenn gilt $I=sY$

$s{\left(\frac{K}{L}\right)}^{\alpha }=\left(\delta +n\right)\left(\frac{K}{L}\right)$

$\iff \left(\frac{s}{\delta +n}\right)={\left(\frac{K}{L}\right)}^{1-\alpha }$

Die gleichgewichtige Kapitalintensität beträgt daher

$\left(\frac{K}{L}\right)={\left(\frac{s}{\delta +n}\right)}^{\frac{1}{1-\alpha }}$

Das gleichgewichtige pro-Kopf-Einkommen ist dann

$y=\left(\frac{Y}{L}\right)={\left(\frac{K}{L}\right)}^{\alpha }={\left(\frac{s}{\delta +n}\right)}^{\frac{\alpha }{1-\alpha }}$

## Technischer Fortschritt/Humankapital

Annahme bislang: $A=1$

Nun Annahme: $A$ wächst mit der konstanten (exogenen) Rate $g$, sodass gilt: $A_{t+1}=(1+g)A_t$

Für das langfristige Gleichgewicht gilt 


Investitionen pro Kopf = Abschreibungen pro Kopf  
$sA(\frac{K}{L})^\alpha=\delta \frac{K}{L}$

$\iff \frac{As}{\delta} = (\frac{K}{L})^\alpha$

$\iff \frac{K}{L}=k=(\frac{As}{\delta})^\frac{1}{1-\alpha}$

$\iff y=(\frac{Y}{L})=(\frac{As}{\delta})^\frac{\alpha}{1-\alpha}$


Wenn $A$ wächst, wächst auch $y$ im Gleichgewicht

In der Literatur wird gelegentlich technischer Fortschritt als erhöhte Arbeitseffizienz dargestellt. Es gilt dann: $Y=K^\alpha(AL)^{1-\alpha}$

Bezeichnet $(\frac{Y}{AN})$ das Einkommen pro Arbeitseffizienzeinheit, lässt sich schreiben $\left(\frac{Y}{AL}\right)=\frac{K^{\alpha }{(AL)}^{1-\alpha }}{AL}=\frac{K^{\alpha }{(AL)}}{(AL){(AL)}^{\alpha }}={\left(\frac{K}{AL}\right)}^{\alpha}$

Die Bedingung für für ein langfristiges Gleichgewicht lautet dann

$s{\left(\frac{K}{AL}\right)}^{\alpha }=\left(\delta +n+g\right)\left(\frac{K}{AL}\right)$

Die Ersparnisse pro Arbeitseffizienzeinheit müssen ausreichen, um die Abschreibungen, das Bevölkerungswachstum und den technischen Fortschritt auszugleichen.

Das gleichgewichtige Einkommen *pro Arbeitseffizienzeinheit* ist dann $\left(\frac{Y}{AL}\right)={\left(\frac{K}{AL}\right)}^{\alpha }={\left(\frac{s}{\delta +n+g}\right)}^{\frac{\alpha }{1-\alpha }}$